// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxDYLmZlvzJgyrby_plHvSFLKXqZNweGI',
    appId: '1:833484254428:web:f02f71bab2973db59a5819',
    messagingSenderId: '833484254428',
    projectId: 'firealertapp-1639f',
    authDomain: 'firealertapp-1639f.firebaseapp.com',
    storageBucket: 'firealertapp-1639f.appspot.com',
    measurementId: 'G-VDDVNWW957',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD65GiwJoTvyYlqngdp3aVwZ6JOI38PScA',
    appId: '1:833484254428:android:4ebacd8517ab39009a5819',
    messagingSenderId: '833484254428',
    projectId: 'firealertapp-1639f',
    storageBucket: 'firealertapp-1639f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD49J99-sYJiqItD-dhA2PC_SCWq_Yw-TA',
    appId: '1:833484254428:ios:6d1434be42b207c79a5819',
    messagingSenderId: '833484254428',
    projectId: 'firealertapp-1639f',
    storageBucket: 'firealertapp-1639f.appspot.com',
    iosBundleId: 'com.example.firealertapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD49J99-sYJiqItD-dhA2PC_SCWq_Yw-TA',
    appId: '1:833484254428:ios:6d1434be42b207c79a5819',
    messagingSenderId: '833484254428',
    projectId: 'firealertapp-1639f',
    storageBucket: 'firealertapp-1639f.appspot.com',
    iosBundleId: 'com.example.firealertapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxDYLmZlvzJgyrby_plHvSFLKXqZNweGI',
    appId: '1:833484254428:web:c5df6a0776474ec39a5819',
    messagingSenderId: '833484254428',
    projectId: 'firealertapp-1639f',
    authDomain: 'firealertapp-1639f.firebaseapp.com',
    storageBucket: 'firealertapp-1639f.appspot.com',
    measurementId: 'G-RLQCMXXF62',
  );
}
